# Generated by Django 3.2.12 on 2022-03-04 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pin',
        ),
    ]
