# Generated by Django 3.2.12 on 2022-03-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pin',
            field=models.CharField(default=22222, max_length=6),
            preserve_default=False,
        ),
    ]
