# Generated by Django 3.2.12 on 2022-03-04 20:29

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='OrderItems',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
