# Generated by Django 3.2.12 on 2022-03-04 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='OrderItems',
        ),
    ]
