# Generated by Django 3.2.12 on 2022-03-04 20:30

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderItems',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
